[package]
name = "r3_support_rp2040"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Supporting package for running R3 on RP2040"
categories = ["embedded", "no-std"]
keywords = ["r3", "arm"]
repository = "https://github.com/r3-os/r3"

[features]
semver-exempt = [
    "embedded-hal",
    "usbd-serial",
    "inline_dyn",
    "usb-device",
    "cortex-m",
    "vcell",
    "nb",
]

[dependencies]
r3_port_arm_m = { version = "0.2.0", path = "../r3_port_arm_m" }
r3_portkit = { version = "0.1.0", path = "../r3_portkit" }
r3 = { version = "0.1.0", path = "../r3" }

embedded-hal = { version = "0.2.4", optional = true }
usbd-serial = { version = "0.1.1", optional = true }
inline_dyn = { version = "0.1.1", optional = true }
rp2040-pac = { version = "0.3.0" }
usb-device = { version = "0.2.7", optional = true }
cortex-m = { version = "0.7.3", optional = true }
vcell = { version = "0.1.2", optional = true }
nb = { version = "1.0.0", optional = true }

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--html-in-header", "src/common.md"]  # [ref:doc_global_styling]
