[package]
name = "r3_port_std"
version = "0.2.1"
description = "Simulator port for the R3-OS original kernel"
keywords = ["r3", "simulator"]

edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
# Used for documentation builds [ref:doc_feature]
doc = []

[dependencies]
r3_core_ks = { version = "0.1.0", path = "../r3_core", package = "r3_core" }
r3_kernel = { version = "0.1.0", path = "../r3_kernel" }

atomic_ref = { version = "0.2.0" }
env_logger = { version = "0.8.4" }
spin = { version = "0.9.2", default-features = false, features = ["spin_mutex"] }
slab = { version = "0.4.5" }
log = { version = "0.4.8" }

[dev-dependencies]
quickcheck_macros = "1.0.0"
quickcheck = "1.0.3"

[dev-dependencies.r3_test_suite]
path = "../r3_test_suite"
default-features = false
features = ["tests_all"]

[target."cfg(unix)".dependencies]
libc = "0.2.71"
errno = "0.2.5"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi", "synchapi", "errhandlingapi", "handleapi"] }

[[bench]]
name = "test_suite"
harness = false

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--html-in-header", "src/common.md"]  # [ref:doc_global_styling]
